INSERT INTO Komenda_Glowna(Komenda_id, adres) VALUES (Komenda_Glowna_Seq.nextval, 'Formosa 74 Crescent Oaks Terrace');
INSERT INTO Komenda_Glowna(Komenda_id, adres) VALUES (Komenda_Glowna_Seq.nextval, 'Randu 0180 Golf Way');
INSERT INTO Komenda_Glowna(Komenda_id, adres) VALUES (Komenda_Glowna_Seq.nextval, 'La Virgen 1253 Thierer Terrace');
INSERT INTO Komenda_Glowna(Komenda_id, adres) VALUES (Komenda_Glowna_Seq.nextval, 'San Rafael 550 Sycamore Plaza');
INSERT INTO Komenda_Glowna(Komenda_id, adres) VALUES (Komenda_Glowna_Seq.nextval, 'Victoria 6110 Stoughton Avenue');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 3, '0 Red Cloud Plaza');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 1, '696 Kenwood Point');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 4, '18383 Mandrake Pass');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 1, '04623 Burning Wood Trail');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 3, '967 Oriole Road');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 2, '295 Grayhawk Drive');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 3, '17 Sachs Alley');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 3, '88 Mitchell Street');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 4, '0460 Shelley Pass');
insert into Posterunki (posterunek_id, FK_id_komendy, adres) values (Posterunki_Seq.nextval, 4, '4 School Court');
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Codi', 'Shirland', 91188582054);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Gayle', 'Dashkovich', 10137670486);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Hilde', 'Beeken', 76858444613);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Heriberto', 'Gradly', 59048546210);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Benson', 'Gidman', 13572338413);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Loralee', 'Whiskin', 98128181624);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Elinore', 'Kermott', 78883937192);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Davin', 'Eschalotte', 86318691758);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Cordi', 'Bugby', 20116334482);
insert into Osoby (osoba_id, imie, nazwisko, Pesel) values (Osoby_Seq.nextval, 'Matthias', 'Fetherstan', 90978271432);
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 7, 'Pobicie', TO_DATE('2019-07-06','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 3, 'Morderstwo', TO_DATE('2019-04-10','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 1, 'Zaklocanie ciszy nocnej', TO_DATE('2019-03-03','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 2, 'Zaklocanie ciszy nocnej', TO_DATE('2019-04-20','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 6, 'Morderstwo', TO_DATE('2019-03-31','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 3, 'Kradziez', TO_DATE('2019-09-23','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 7, 'Kradziez', TO_DATE('2019-03-22','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 9, 'Pobicie', TO_DATE('2019-03-07','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 6, 'Morderstwo', TO_DATE('2019-09-01','YY-MM-DD'));
insert into Zgloszenia (zgloszenie_id, FK_id_osoby, typ_zdarzenia, data_zgloszenia) values (Zgloszenia_Seq.nextval, 6, 'Pobicie', TO_DATE('2019-07-31','YY-MM-DD'));
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 4, 5);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 6, 7);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 2, 8);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 10, 4);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 4, 3);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 9, 8);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 6, 3);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 1, 5);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 2, 10);
insert into Zgloszenia_posterunku (zgloszenie_posterunku_id, FK_id_zgloszenia, FK_id_posterunku) values (Zgloszenia_posterunku_Seq.nextVal, 3, 4);
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 7, TO_DATE('2019-11-23','YYYY-MM-DD'), 'Morderstwo');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 10, TO_DATE('2019-08-16','YYYY-MM-DD'), 'Zaklocanie ciszy nocnej');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 9, TO_DATE('2019-04-20','YYYY-MM-DD'), 'Zaklocanie ciszy nocnej');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 4, TO_DATE('2019-09-22','YYYY-MM-DD'), 'Pobicie');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 3, TO_DATE('2019-04-01','YYYY-MM-DD'), 'Morderstwo');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 3, TO_DATE('2019-02-18','YYYY-MM-DD'), 'Pobicie');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 2, TO_DATE('2019-11-03','YYYY-MM-DD'), 'Niszczenie Mienia');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 4, TO_DATE('2019-05-03','YYYY-MM-DD'), 'Niszczenie Mienia');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 9, TO_DATE('2019-08-11','YYYY-MM-DD'), 'Pobicie');
insert into Wykroczenia (wykroczenie_id, FK_id_osoby, data_wykroczenia, typ_wykroczenia) values (Wykroczenia_Seq.nextval, 8, TO_DATE('2019-11-17','YYYY-MM-DD'), 'Zaklocanie ciszy nocnej');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Aresztowanie', 0, 'Odsiadka');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Mandat', 4980, 'Zaplata_Mandatu');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Mandat', 6314, 'Zaplata_Mandatu');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Aresztowanie', 0, 'Odsiadka');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Aresztowanie', 0, 'Odsiadka_Mandatu');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Mandat', 1511, 'Zaplata_Mandatu');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Aresztowanie', 0, 'Odsiadka');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Mandat', 1523, 'Zaplata_Mandatu');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Mandat', 8453, 'Zaplata_Mandatu');
insert into Kary (kara_id, typ_kary, Kwota, Wyrok) values (Kary_Seq.nextval, 'Mandat', 6256, 'Zaplata_Mandatu');
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 4, 2);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 5, 2);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 9, 1);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 2, 2);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 9, 4);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 8, 3);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 3, 6);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 6, 2);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 2, 9);
insert into Kary_za_wykroczenia (kara_za_wykroczenie_id, FK_id_kary, FK_id_wykroczenia) values (Kary_za_wykroczenia_Seq.nextval, 1, 7);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 6, 'Kathryne', 'Boatright', 53469989538, 'Policjant', 93);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 8, 'Rica', 'Feavers', 24016988296, 'Policjant', 25);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 8, 'Valaree', 'Gummory', 40914525032, 'Policjant', 34);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 9, 'Keeley', 'Rockcliff', 11205031595, 'Recepcjonista', 26);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 8, 'Giff', 'Lebourn', 94255094158, 'Policjant', 19);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 1, 'Nonah', 'Mawne', 58808237910, 'Policjant', 23);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 2, 'Heidi', 'Cicci', 45320619781, 'Policjant', 62);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 7, 'Neel', 'Presslee', 15614718605, 'Seketarka', 41);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 1, 'Lindsay', 'Jozwik', 13654997280, 'Policjant', 75);
insert into Pracownicy (pracownik_id, FK_id_posterunku, Imie, Nazwisko, Pesel, Stanowisko, Wiek) values (Pracownicy_Seq.nextval, 1, 'Blythe', 'Flear', 67295788946, 'Sprzataczka', 73);
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Odzyskiwania_Mienia');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Poszukiwan');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Kryminalny');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Dochodzeniowo-Sledczy');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Korupcyjny');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Odzyskiwania_Mienia');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Korupcyjny');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Ogolny');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Ogolny');
insert into Wydzialy (wydzial_id, nazwa) values (Wydzialy_Seq.nextval, 'Dochodzeniowo-Sledczy');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 1, 10, 1, 'Posterunkowy');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 2, 6, 2, 'Inspektor');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 3, 1, 3, 'Inspektor');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 5, 2, 4, 'Aspirant');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 6, 8, 5, 'Inspektor');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 7, 9, 6, 'Komisarz');
insert into Policjanci (policjant_id, FK_id_pracownika, FK_id_wydzialu, Numer_odznaki, Ranga) values (Policjanci_Seq.nextval, 9, 5, 7, 'Posterunkowy');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 5, 'auto', 'Pontiac');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 7, 'bron', 'GLOCK18');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 5, 'auto', 'BMW');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 7, 'bron','AK47');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 2, 'bron', 'Paralizator');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 2, 'bron', 'GLOCK18');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 9, 'bron', 'GLOCK18');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 2, 'auto', 'Saab');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 2, 'bron', 'GLOCK18');
insert into Zasoby (zasob_id, FK_id_pracownika, rodzaj, nazwa) values (Zasoby_Seq.nextval, 10, 'auto', 'Buick');
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 5, 2);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 3, 6);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 10, 7);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 4, 4);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 9, 6);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 3, 5);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 3, 3);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 7, 3);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 9, 7);
insert into Czynosci_Policjantow (Czynosci_Policjantow_id, FK_id_wykroczenia, FK_id_Policjanta) values (Czynosci_Policjantow_Seq.nextval, 10, 7);